services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: blog-db
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
    ports:
      - "5433:5432"
    restart: always

volumes:
  postgres_data:
